import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/templates/footer/page";
import Header from "@/templates/header/page";
import BackToTop from "@/components/BackToTop";
import ProviderWrapper from "./providers/providerWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "H7 Life",
  description: "Generated by H7 Life",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderWrapper>
          <Header />
          {children}
          <Footer />
          <BackToTop />
        </ProviderWrapper>
      </body>
    </html>
  );
}
